import 'tile.dart';

class SwapMove {
  const SwapMove({
    required this.row,
    required this.col,
  });

  final int row;
  final int col;
}

final List<SwapMove> moves = [
  const SwapMove(row: 0, col: -1),
  const SwapMove(row: 0, col: 1),
  const SwapMove(row: -1, col: 0),
  const SwapMove(row: 1, col: 0),
];

Map<TileType, List<SwapMove>> explosions = {
  TileType.bomb_h: <SwapMove>[
    const SwapMove(row: 0, col: -1),
    const SwapMove(row: 0, col: -2),
    const SwapMove(row: 0, col: -3),
    const SwapMove(row: 0, col: -4),
    const SwapMove(row: 0, col: -5),
    const SwapMove(row: 0, col: -6),
    const SwapMove(row: 0, col: -7),
    const SwapMove(row: 0, col: -8),
    const SwapMove(row: 0, col: -9),
    const SwapMove(row: 0, col: -10),
    const SwapMove(row: 0, col: 0),
    const SwapMove(row: 0, col: 1),
    const SwapMove(row: 0, col: 2),
    const SwapMove(row: 0, col: 3),
    const SwapMove(row: 0, col: 4),
    const SwapMove(row: 0, col: 5),
    const SwapMove(row: 0, col: 6),
    const SwapMove(row: 0, col: 7),
    const SwapMove(row: 0, col: 8),
    const SwapMove(row: 0, col: 9),
    const SwapMove(row: 0, col: 10),
  ],
  TileType.bomb_v: <SwapMove>[
    const SwapMove(col: 0, row: -1),
    const SwapMove(col: 0, row: -2),
    const SwapMove(col: 0, row: -3),
    const SwapMove(col: 0, row: -4),
    const SwapMove(col: 0, row: -5),
    const SwapMove(col: 0, row: -6),
    const SwapMove(col: 0, row: -7),
    const SwapMove(col: 0, row: -8),
    const SwapMove(col: 0, row: -9),
    const SwapMove(col: 0, row: -10),
    const SwapMove(col: 0, row: 0),
    const SwapMove(col: 0, row: 1),
    const SwapMove(col: 0, row: 2),
    const SwapMove(col: 0, row: 3),
    const SwapMove(col: 0, row: 4),
    const SwapMove(col: 0, row: 5),
    const SwapMove(col: 0, row: 6),
    const SwapMove(col: 0, row: 7),
    const SwapMove(col: 0, row: 8),
    const SwapMove(col: 0, row: 9),
    const SwapMove(col: 0, row: 10),
  ],
  TileType.flare: <SwapMove>[
    const SwapMove(row: 0, col: -1),
    const SwapMove(row: 0, col: 1),
    const SwapMove(row: -1, col: 0),
    const SwapMove(row: 1, col: 0),
    const SwapMove(row: 0, col: 0),
  ],
  TileType.bomb: <SwapMove>[
    const SwapMove(row: 0, col: -2),
    const SwapMove(row: 0, col: -1),
    const SwapMove(row: 0, col: 1),
    const SwapMove(row: 0, col: 2),
    const SwapMove(row: -1, col: 0),
    const SwapMove(row: -1, col: -1),
    const SwapMove(row: -1, col: 1),
    const SwapMove(row: 1, col: -1),
    const SwapMove(row: 1, col: 0),
    const SwapMove(row: 1, col: 1),
    const SwapMove(row: -2, col: 0),
    const SwapMove(row: 2, col: 0),
    const SwapMove(row: 0, col: 0),
  ],
  TileType.wrapped: <SwapMove>[
    const SwapMove(row: 0, col: -3),
    const SwapMove(row: 0, col: -2),
    const SwapMove(row: 0, col: -1),
    const SwapMove(row: 0, col: 1),
    const SwapMove(row: 0, col: 2),
    const SwapMove(row: 0, col: 3),
    const SwapMove(row: -1, col: -2),
    const SwapMove(row: -1, col: -1),
    const SwapMove(row: -1, col: 0),
    const SwapMove(row: -1, col: 1),
    const SwapMove(row: -1, col: 2),
    const SwapMove(row: 1, col: -2),
    const SwapMove(row: 1, col: -1),
    const SwapMove(row: 1, col: 0),
    const SwapMove(row: 1, col: 1),
    const SwapMove(row: 1, col: 2),
    const SwapMove(row: -2, col: -1),
    const SwapMove(row: -2, col: 0),
    const SwapMove(row: -2, col: 1),
    const SwapMove(row: 2, col: -1),
    const SwapMove(row: 2, col: 0),
    const SwapMove(row: 2, col: 1),
    const SwapMove(row: -3, col: 0),
    const SwapMove(row: 3, col: 0),
    const SwapMove(row: 0, col: 0),
  ],
};
